services:
  - type: web
    name: story-generator-api-ynk2
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip config set global.timeout 1000
      pip install wheel
      pip install -r requirements.txt --no-cache-dir --timeout 1000
    startCommand: |
      python main.py
    memory: 1024
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_S3_MODEL_KEY
        sync: false
      - key: AWS_REGION
        sync: false
    healthCheckPath: /health
    autoDeploy: true 