services:
  - type: web
    name: story-generator-api-ynk2
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip config set global.timeout 1000
      pip install wheel
      pip install -r requirements.txt --no-cache-dir --timeout 1000
    startCommand: |
      python -m uvicorn main:app --host 0.0.0.0 --port 10000
    memory: 512
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 